// <auto-generated />
using System;
using Flower.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flower.Infrastructure.Migrations
{
    [DbContext(typeof(FlowerDbContext))]
    partial class FlowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flower.Domain.Entities.FlowerProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FlowerProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "bouquet",
                            Code = "FLR-001",
                            IsAvailable = true,
                            Name = "Pembe Gül Buketi",
                            Price = 850m
                        },
                        new
                        {
                            Id = 2,
                            Category = "orchid",
                            Code = "FLR-002",
                            IsAvailable = true,
                            Name = "Beyaz Orkide",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 3,
                            Category = "bouquet",
                            Code = "FLR-003",
                            IsAvailable = true,
                            Name = "Kırmızı Güller 11’li",
                            Price = 690m
                        },
                        new
                        {
                            Id = 4,
                            Category = "mixed",
                            Code = "FLR-004",
                            IsAvailable = true,
                            Name = "Mevsim Çiçekleri Vazoda",
                            Price = 540m
                        },
                        new
                        {
                            Id = 5,
                            Category = "orchid",
                            Code = "FLR-005",
                            IsAvailable = true,
                            Name = "Saksı Orkide Çift Dal",
                            Price = 1450m
                        },
                        new
                        {
                            Id = 6,
                            Category = "terrarium",
                            Code = "FLR-006",
                            IsAvailable = true,
                            Name = "Teraryum Küçük Dünya",
                            Price = 820m
                        },
                        new
                        {
                            Id = 7,
                            Category = "ceremony",
                            Code = "FLR-007",
                            IsAvailable = true,
                            Name = "Söz – Nişan Masası Çiçeği",
                            Price = 1950m
                        },
                        new
                        {
                            Id = 8,
                            Category = "birthday",
                            Code = "FLR-008",
                            IsAvailable = true,
                            Name = "Doğum Günü Pembe Aranjman",
                            Price = 780m
                        });
                });

            modelBuilder.Entity("Flower.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
